videoMode db 13h
windowWidth dw 320d
windowHeight dw 200d

backgroundColor db 08h
pixelColor db 0dh

padWidth db 80d
padHeight db 5d
padColor db 22h
padOutlineColor db 00h

brickWidth db 20d
brickHeight db 10d
brickLayerCount db 14d

brickColor db 27h
brickPrimaryColor db 27h
brickPrimaryLightColor db 6fh
brickSecondaryColor db
brickSecondaryLightColor db 
brickSpecialColor db 36h
brickOutlineColor db 00h

levelOneLayers db 7d
